# Generated by Django 5.2.1 on 2025-05-09 00:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='nota',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Nota'),
        ),
    ]
